/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_admin_peacezone_JniTest */

#ifndef _Included_com_example_admin_peacezone_JniTest
#define _Included_com_example_admin_peacezone_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_admin_peacezone_JniTest
 * Method:    CreateServer
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_peacezone_JniTest_CreateServer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_admin_peacezone_JniTest
 * Method:    CreateClient
 * Signature: (Ljava/lang/String;I)C
 */
JNIEXPORT jchar JNICALL Java_com_example_admin_peacezone_JniTest_CreateClient
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_admin_peacezone_JniTest
 * Method:    OnDataRecvCallFunc
 * Signature: (CIJICLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_admin_peacezone_JniTest_OnDataRecvCallFunc
  (JNIEnv *, jobject, jchar, jint, jlong, jint, jchar, jstring, jstring);

/*
 * Class:     com_example_admin_peacezone_JniTest
 * Method:    SendData
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_admin_peacezone_JniTest_SendData
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_example_admin_peacezone_JniTest
 * Method:    FreeNet
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_admin_peacezone_JniTest_FreeNet
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
